### PR TITLE
Update to Lean 4.8.0

### PR DESCRIPTION
**Pull request by girving**

### CODE REVIEW

**Comment by eric-wieser** [comment]
Please can you resolve the conflicts? Feel free to take your resolutions over the ones I introduced with the 4.7.0 update.

**Comment by eric-wieser** [comment]
Nevermind, I did the merge for you keeping all your changes. Please take a look over the result, and clean up any diffs that no longer makes sense.

Also, I think it would make more sense to bump to 4.8.0 (rather than the rc), or skip straight to 4.10.0

**Comment by girving** [comment]
I also already did the merge, just haven’t pushed yet.

**Comment by girving** [comment]
Would you be okay pausing on further detail changes? I’m a bit worried I have to redo all of my merge now.

**Comment by girving** [comment]
I have a lot of downstream changes as well.

**Comment by girving** [comment]
Actually let's hold off on the 4.10 upgrade, since I have a few more PRs to get in after this, and merging them prior to the upgrade will be easier.

**Comment by girving** [comment]
On v4.8.0 exactly now, rather than -rc2.

**Review by eric-wieser — APPROVED** [review]

**Pull request merged**
